#ifndef ELI_MBEDTLS_CONFIG_H
#define ELI_MBEDTLS_CONFIG_H

/* eli uses mbedtls only as a TLS client over stream sockets. Trim what the
 * default config keeps reachable but eli never uses: TLS server/DTLS, session
 * tickets, persistent PSA storage, x509 write/CRL/CSR/PKCS7/PKCS12, legacy
 * ciphers (3DES, Camellia, ARIA) and rare curves (Brainpool, secp192/224,
 * secp256k1, X448). AES, ChaCha20-Poly1305, secp256r1/384r1/521r1 and X25519
 * remain enabled. */
#undef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_SSL_PROTO_DTLS
#undef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT
#undef MBEDTLS_SSL_COOKIE_C
#undef MBEDTLS_SSL_SESSION_TICKETS
#undef MBEDTLS_TIMING_C

#undef MBEDTLS_X509_CRL_PARSE_C
#undef MBEDTLS_X509_CSR_PARSE_C
#undef MBEDTLS_X509_CRT_WRITE_C
#undef MBEDTLS_PEM_WRITE_C
#undef MBEDTLS_PKCS7_C
#undef MBEDTLS_PKCS12_C

#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_ITS_FILE_C

#undef MBEDTLS_DES_C
#undef MBEDTLS_CAMELLIA_C
#undef MBEDTLS_ARIA_C

#undef MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_CURVE448_ENABLED

#endif /* ELI_MBEDTLS_CONFIG_H */
