name: prepare-test
description: downloads and chmods artifacts

runs:
  using: "composite"
  steps:
  - name: prepare
    run: mkdir release

  - uses: actions/download-artifact@v4
    with:
      path: ./release
      pattern: release-*
      merge-multiple: true

  - name: make executable
    if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
    shell: sh
    run: chmod +x ./release/* && ls -la ./release/*
