name: prepare-test

runs:
  using: "composite"
  steps:
  - uses: actions/download-artifact@v3
    with:
      path: ./release
  - name: make executable
    if: runner.os == 'Linux' || runner.os == 'macOS'
    run: chmod +x ./release/*