name: build-n-cache

inputs:
  toolchain:
    required: true
  artifact-id:
    required: true
  debug-artifact-id:
    required: false

runs:
  using: "composite"
  steps:
  - name: build
    uses: addnab/docker-run-action@v3
    with:
      image: ghcr.io/alis-is/eli-build:latest
      run: eli tools/build.lua
      options: -w /root/luabuild -v ${{ github.workspace }}:/root/luabuild -e TOOLCHAINS=${{ inputs.toolchain }}
  - name: build
    uses: addnab/docker-run-action@v3
    if: ${{ inputs.debug-artifact-id != '' }}
    with:
      image: ghcr.io/alis-is/eli-build:latest
      run: eli tools/build.lua --debug
      options: -w /root/luabuild -v ${{ github.workspace }}:/root/luabuild -e TOOLCHAINS=${{ inputs.toolchain }}

  - uses: actions/upload-artifact@v4
    with:
      name: release-${{ inputs.artifact-id }}
      path: ./release/${{ inputs.artifact-id }}

  - uses: actions/upload-artifact@v4
    if: ${{ inputs.debug-artifact-id != '' }}
    with:
      name: debug-${{ inputs.debug-artifact-id }}
      path: ./release/${{ inputs.debug-artifact-id }}

  - uses: actions/upload-artifact@v4
    with:
      name: release
      path: ./release/meta.zip
      if-no-files-found: ignore # meta is generated only on x86_64 linux
