name: build-n-cache

inputs:
  toolchain:
    require: true
  artifact-id:
    require: true

runs:
  using: "composite"
  steps:
  - name: build
    uses: addnab/docker-run-action@v3
    with:
      image: ghcr.io/alis-is/eli-build:latest
      run: ./eli tools/build.lua
      options: -w /root/luabuild -v ${{ github.workspace }}:/root/luabuild -e TOOLCHAINS=${{ inputs.toolchain }}
  - uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.artifact-id }}
      path: ./release/${{ inputs.artifact-id }}
  - uses: actions/upload-artifact@v3
    with:
      name: meta.zip
      path: ./release/meta.zip
      if-no-files-found: ignore # meta is generated only on x86_64 linux