name: build-n-cache

# Were we can define the inputs that our action will accept
inputs:
  toolchain:
    require: true
  cache-id:
    require: true

runs:
  using: "composite"
  steps:
  - name: restore cache
    uses: actions/cache/restore@v3
    with:
      path: ./release
      key: ${{ inputs.cache-id }}
      enableCrossOsArchive: true
  - name: build
    uses: addnab/docker-run-action@v3
    with:
      image: ghcr.io/alis-is/eli-build:latest
      run: ./eli tools/build.lua
      options: -w /root/luabuild -v ${{ github.workspace }}:/root/luabuild -e TOOLCHAINS=${{ inputs.toolchain }}
  - name: cache release
    uses: actions/cache/save@v3
    with:
      path: ./release
      key: ${{ inputs.cache-id }}
      enableCrossOsArchive: true