name: release

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      NEEDS_RELEASE: ${{ steps.prep.outputs.NEEDS_RELEASE }}
      VERSION: ${{ steps.prep.outputs.VERSION }}
      PRERELEASE: ${{ steps.prep.outputs.PRERELEASE }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup eli
        uses: alis-is/setup-eli@v1
      - name: prepare
        id: prep
        shell: sh
        run: |
          PLATFORM=$(uname -m) && echo "PLATFORM=$PLATFORM" >> $GITHUB_OUTPUT
          ROOT=$(pwd) && echo "ROOT=$ROOT" >> $GITHUB_OUTPUT
          rm -rf release .meta
          mkdir -p "$ROOT/release"
          VERSION=$(eli -e 'io.write(require"hjson".parse(fs.read_file"config.hjson").version)')
          # if VERSION is just 'dev' then we do not need to release
          if [ "$VERSION" = "dev" ]; then
            NEEDS_RELEASE=false
            echo "NEEDS_RELEASE=$NEEDS_RELEASE" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          if git tag -l "$VERSION" | grep "$VERSION"; then 
            echo "Version $VERSION already exists";
          else
            NEEDS_RELEASE=true
            echo "NEEDS_RELEASE=$NEEDS_RELEASE" >> $GITHUB_OUTPUT
          fi
          if echo "$VERSION" | grep -E "dev|alpha"; then
            PRERELEASE=true
            echo "PRERELEASE=$PRERELEASE" >> $GITHUB_OUTPUT
          fi
          echo "Building eli $VERSION (RELEASE_REQUIRE: $NEEDS_RELEASE)"

  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    if: ${{ needs.prepare.outputs.NEEDS_RELEASE == 'true' }}
    runs-on: ubuntu-latest
    needs: [ci, prepare]
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/template/prepare-test" # downloads artifacts

      - name: publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./release/*
          tag: ${{ needs.prepare.outputs.VERSION }}
          commit: ${{ github.sha }}
          prerelease: ${{needs.prepare.outputs.PRERELEASE}}
